import SidebarComponent from "@/components/SidebarComponent";
import "./globals.css";
import NavbarComponent from "@/components/NavbarComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        <main className="layout grid grid-cols-[305px_1fr]">
          <SidebarComponent />
          <section className="right-side grid grid-rows-[auto_1fr]">
            <NavbarComponent />
            <main>
              <section className="path-link">
                <p>gjeweefdwh </p>
              </section>
              {children}
            </main>
          </section>
        </main>
      </body>
    </html>
  );
}
